// Reads docs/PRIVACY.md and docs/TERMS.md and emits docs/embedded.ts so the
// App.tsx bundle can import those documents on every platform (web + native).
// Re-run after editing either file:  node scripts/embed-docs.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");

function read(name) {
  try {
    return readFileSync(join(ROOT, "docs", name), "utf8").trimEnd();
  } catch {
    return "";
  }
}

const privacy = read("PRIVACY.md");
const terms = read("TERMS.md");

const out = `// AUTO-GENERATED by scripts/embed-docs.mjs — do not edit by hand.
// Edit docs/PRIVACY.md or docs/TERMS.md and re-run the script.

export const PRIVACY_DOC = ${JSON.stringify(privacy)};
export const TERMS_DOC = ${JSON.stringify(terms)};
`;

writeFileSync(join(ROOT, "docs", "embedded.ts"), out, "utf8");
console.log(
  `Wrote docs/embedded.ts — privacy=${privacy.length} chars, terms=${terms.length} chars`,
);
