// AUTO-GENERATED by scripts/embed-docs.mjs — do not edit by hand.
// Edit docs/PRIVACY.md or docs/TERMS.md and re-run the script.

export const PRIVACY_DOC = "# Privacy Policy\n\n_Last updated: TODO_\n\n> Placeholder — fill this in with the production privacy policy. The H2O to You app currently keeps everything local (AsyncStorage on the device). No analytics, advertising, or third-party tracking SDKs are bundled.";
export const TERMS_DOC = "# Terms of Service\n\n_Last updated: TODO_\n\n> Placeholder — fill this in with the production terms of service. Reservoir, snowpack, and precipitation values shown in the app are sourced from the California Data Exchange Center (CDEC) and are provisional; H2O to You is not responsible for operational decisions made on the basis of those readings.";
